sudo: required
dist: trusty
language: node_js
services:
- postgresql
node_js:
- '7'
rvm:
- 2.3.1
addons:
  firefox: '56.0b1'
  postgresql: '9.4'
before_install:
# env
- export DISPLAY=':99.0'
- export CI=false
# dependencies
- sudo apt-get -qq update
- sudo apt-get install ruby ruby-dev xvfb autoconf automake libtool redis-server -y
- rvm install 2.3.1
- rvm --default use 2.3.1
- gem install bundler
# check api
- psql -c 'create database checkdesk_development;' -U postgres
- redis-server 2>&1 >/dev/null &
- wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.1.deb && sudo service elasticsearch restart
- sleep 15
- 'echo "script.engine.groovy.inline.update: on" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
- sudo /usr/share/elasticsearch/bin/plugin install analysis-icu
- sudo service elasticsearch restart
- git clone https://github.com/meedan/check-api.git
- cp check-api/config/config.yml.example check-api/config/config.yml
- cp check-api/config/initializers/secret_token.rb.example check-api/config/initializers/secret_token.rb
- cp check-api/config/database.yml.example check-api/config/database.yml
- sed -i s/host: postgres/host: localhost/ check-api/config/database.yml 
- cd check-api
- bundle install
- bundle exec rake db:migrate
- bundle exec rake lapis:api_keys:create_default
- rails s -p 3000 >/dev/null &
- cd -
# watchman (relay-compiler dependency)
- git clone https://github.com/facebook/watchman.git
- cd watchman
- git checkout v4.7.0
- ./autogen.sh
- ./configure --without-python
- make
- sudo make install
- cd -
# xvfb
- sh -e /etc/init.d/xvfb start
# google chrome
- sudo apt-get -qq update
- sudo apt-get install chromium-browser -y
- export CHROME_BIN=/usr/bin/chromium-browser
- chromium-browser --no-sandbox &
# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver >/dev/null 2>/dev/null &
# geckodriver
- wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- geckodriver -p 4445 >/dev/null 2>/dev/null &
# test dependencies
- cd test && bundle install && cd -
# configs
- cp config.js.travis config.js
- cp config.js.travis config.js.test
- cp test/config.yml.travis test/config.yml
before_script:
- npm install
script: npm run test
